### ISSUE TITLE
Review github3.py

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-sdk-py#33]
Ian Cordasco's https://github.com/sigmavirus24/github3.py has some cool features and the Python community likes it. We should review and consider its model.

Particularly interesting is its `login` pattern

```python
from github3 import login

g = login(user, password)
```

and the example of updating a user in two difference ways at https://github3py.readthedocs.org/en/master/examples/github.html#changing-your-user-information. One less resource-oriented:

```python
new_name = 'J. Smith'
blog = 'http://www.example.com/'
company = 'Vandelay Industries'
bio = """# J. Smith

A simple man working at a latex factory
"""

if g.update_user(new_name, blog, company, bio=bio):
    print('Profile updated.')
```

and one more resource-oriented:

```python
me = g.user()
if me.update(new_name, blog, company, bio=bio):
    print('Profile updated.')
```

**Comment by perrygeo** [comment]
I was curious about the two ways to update, looks like they've [removed it](https://github.com/sigmavirus24/github3.py/commit/a03fd6d3e213ea8947b595617ba988bfa6438f30) but haven't updated the docs. Probably a good move since the code was redundant - in this particular case you can't update any user but the one you're logged in as.

For purposes of other APIs like Datasets it might be nice to support both patterns if we could avoid code duplication (`feature.update(..)` could just dispatch to `g.update_feature(id, ...)`)

**Comment by sgillies** [comment]
The Mapbox javascript SDK is a lot more like github3py than the Python one is: a single API endpoint object with many methods spanning all the GitHub resources. And the network is hidden. After considering this last night, I'm open to making the Python SDK more like this and less of a special snowflake.

One big difference between GitHub and Mapbox is that the former's API is versioned as a single thing and the latter has multiple APIs versioned separately with varying degree of integration between them. That's what has motivated me to create different service classes (Geocoder, Datasets, etc).

**Comment by perrygeo** [comment]
I was starting to like the idea of exposing http responses directly. But there are advantages to hiding the network, mainly that you can raise appropriate exceptions based on the return status.

Because of the independent nature of the mapbox APIs (different versions, different levels of maturity, etc), I think separate service classes makes sense.  The javascript sdk implicitly acknowledges that with the [sub-requires](https://github.com/mapbox/mapbox-sdk-js#sub-requiring-individual-services) approach but I don't think that would be a good fit for Python.

**Comment by sgillies** [comment]
Conclusion: we're sticking with responses from Requests. This SDK is in that sense lower level than github3.py.
