### ISSUE TITLE
Raise exceptions on HTTP errors

### ISSUE THREAD

**Issue by perrygeo** [mapbox/mapbox-sdk-py#45]
http://www.python-requests.org/en/latest/user/quickstart/#response-status-codes

`response.raise_for_status()` will raise an `HTTPError` if not successful, returns None otherwise

**Comment by perrygeo** [comment]
So this is nice but causes two problems:

1. This: https://github.com/kennethreitz/requests/issues/2402 - `raise_for_status()` doesn't display the message body and this hides potentially useful messages from the users. Possible solution is just to make our own custom function to include the message body.

2. The CLI does not expect exceptions: https://github.com/mapbox/mapbox-sdk-py/blob/master/mapbox/scripts/geocoder.py#L91 . That behavior would need to be modified with a try/except

**Comment by sgillies** [comment]
In my experience with the Mapbox APIs (I wrote a small part of them), they don't return unprintable characters or binary data in error messages, so we'll be able to add message bodies in our exception handlers. Using logging instead of printing.

What if we added a flag for whether we wanted to call `raise_for_status()` to the service object constructor and call that method only if the flag is true? Then the CLI could just do

```python
from geocoding import Geocoder

geocoder = Geocoder(..., raise_for_status=False)
...
```

if you see what I mean.

**Comment by sgillies** [comment]
Now I'm flip-flopping... requests leaves raise_for_status up to the user, which signals to me that we might want to try that for starters, too. So, how about `raise_for_status=False` as the default for services?

**Comment by perrygeo** [comment]
How about this? Instead of using `response.raise_for_status()` everywhere, we add a method to the base `Service` class. Every method would have access to `self.handle_http_error(response)` which would be configured on init. Handling an http error could either raise an exception, raise an exception with the message body, warn, or pass silently.

**Comment by sgillies** [comment]
:+1:
